version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 95

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "isort"
enabled = true
